version: '3.8'

services:
  django:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - DJANGO_SETTINGS_MODULE=cartera_clientes.settings
      - ALLOWED_HOSTS=139.177.101.46,localhost,127.0.0.1
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    # --- AÑADIDO ---
    networks:
      - red_proxy

volumes:
  static_volume:
  media_volume:

# --- AÑADIDO ---
networks:
  red_proxy:
    external: true