version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: cartera_clientes_db
      MYSQL_ROOT_PASSWORD: Filipenses4:13
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - red_proxy
    restart: unless-stopped

  django:
    build: .
    ports:
      - "8989:8000"
    environment:
      - DEBUG=False
      - DJANGO_SETTINGS_MODULE=cartera_clientes.settings
      - ALLOWED_HOSTS=*
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - mysql
    restart: unless-stopped
    networks:
      - red_proxy

volumes:
  mysql_data:
  static_volume:
  media_volume:

networks:
  red_proxy:
    external: true