version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: cartera_clientes_db
      MYSQL_ROOT_PASSWORD: Filipenses4:13
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    restart: unless-stopped

  django:
    build: .
    ports:
      - "8989:8000"
    environment:
      - DEBUG=False
      - DJANGO_SETTINGS_MODULE=cartera_clientes.settings
      - ALLOWED_HOSTS=*
      - DB_HOST=mysql
      - DB_NAME=cartera_clientes_db
      - DB_USER=root
      - DB_PASSWORD=Filipenses4:13
      - DB_PORT=3306
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - mysql
    restart: unless-stopped

volumes:
  mysql_data:
  static_volume:
  media_volume: