version: '3.8'

services:
  django:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - DJANGO_SETTINGS_MODULE=cartera_clientes.settings
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    network_mode: host
    restart: unless-stopped

volumes:
  static_volume:
  media_volume: