# Generated by Django 5.2.3 on 2025-06-29 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_cliente_todoitem_cliente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoitem',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Oportunidad de Venta', 'verbose_name_plural': 'Oportunidades de Ventas'},
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='asignado_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='contacto_principal',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Contacto Principal'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre_empresa',
            field=models.CharField(max_length=200, unique=True, verbose_name='Nombre de la Empresa'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='area',
            field=models.CharField(choices=[('servicios', 'Servicios'), ('productos', 'Productos'), ('consultoria', 'Consultoría'), ('software', 'Software')], max_length=50, verbose_name='Área'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidades', to='app.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='contacto',
            field=models.CharField(max_length=200, verbose_name='Contacto del Cliente'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='mes_cierre',
            field=models.CharField(choices=[('01', 'Enero'), ('02', 'Febrero'), ('03', 'Marzo'), ('04', 'Abril'), ('05', 'Mayo'), ('06', 'Junio'), ('07', 'Julio'), ('08', 'Agosto'), ('09', 'Septiembre'), ('10', 'Octubre'), ('11', 'Noviembre'), ('12', 'Diciembre')], max_length=2, verbose_name='Mes de Cierre Esperado'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto de la Oportunidad'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='oportunidad',
            field=models.CharField(max_length=200, verbose_name='Oportunidad de Venta'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='probabilidad_cierre',
            field=models.IntegerField(default=0, verbose_name='Probabilidad de Cierre (%)'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='producto',
            field=models.CharField(choices=[('licencia_sw', 'Licencia de Software'), ('hardware', 'Hardware'), ('implementacion', 'Implementación'), ('soporte', 'Soporte'), ('entrenamiento', 'Entrenamiento'), ('hosting', 'Hosting'), ('custom_dev', 'Desarrollo a la Medida')], max_length=50, verbose_name='Producto / Servicio'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='oportunidades_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creador'),
            preserve_default=False,
        ),
    ]
