# Generated by Django 5.2.3 on 2025-06-29 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_todoitem_options_remove_cliente_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='area',
            field=models.CharField(choices=[('Compras', 'Compras'), ('Sistemas', 'Sistemas'), ('Facilities', 'Facilities'), ('RH', 'RH'), ('Almacen', 'Almacén'), ('Seguridad', 'Seguridad')], max_length=50, verbose_name='Área'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='producto',
            field=models.CharField(choices=[('ZEBRA', 'ZEBRA'), ('PANDUIT', 'PANDUIT'), ('APC', 'APC'), ('AVIGILON', 'AVIGILON'), ('GENETEC', 'GENETEC'), ('AXIS', 'AXIS'), ('Desarrollo APP', 'Desarrollo APP'), ('RUNRATE', 'RUNRATE'), ('Poliza', 'Poliza'), ('CISCO', 'CISCO'), ('HARDWARE', 'HARDWARE'), ('SOFTWARE', 'SOFTWARE')], max_length=50, verbose_name='Producto / Servicio'),
        ),
    ]
