# Generated by Django 5.2.3 on 2025-06-30 05:51

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_todoitem_area_alter_todoitem_producto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoitem',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Oportunidad de Venta', 'verbose_name_plural': 'Oportunidades de Venta'},
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='contacto_principal',
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todoitem',
            name='fecha_limite',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='asignado_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre_empresa',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='area',
            field=models.CharField(choices=[('TI', 'Tecnología de la Información'), ('VENTAS', 'Ventas'), ('MARKETING', 'Marketing'), ('FINANZAS', 'Finanzas'), ('RRHH', 'Recursos Humanos'), ('OPERACIONES', 'Operaciones'), ('OTRO', 'Otro')], max_length=50),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidades', to='app.cliente'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='contacto',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='mes_cierre',
            field=models.CharField(choices=[('01', 'Enero'), ('02', 'Febrero'), ('03', 'Marzo'), ('04', 'Abril'), ('05', 'Mayo'), ('06', 'Junio'), ('07', 'Julio'), ('08', 'Agosto'), ('09', 'Septiembre'), ('10', 'Octubre'), ('11', 'Noviembre'), ('12', 'Diciembre')], default='01', max_length=2),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='oportunidad',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='probabilidad_cierre',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='producto',
            field=models.CharField(choices=[('ZEBRA', 'Zebra'), ('PANDUIT', 'Panduit'), ('APC', 'APC'), ('AVIGILON', 'Avigilon'), ('AXIS', 'Axis'), ('DESARROLLO APP', 'Desarrollo de Aplicaciones'), ('RUNRATE', 'RunRate'), ('POLIZA', 'Póliza'), ('CISCO', 'Cisco'), ('HARDWARE', 'Hardware'), ('SOFTWARE', 'Software')], max_length=100),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oportunidades', to=settings.AUTH_USER_MODEL),
        ),
    ]
