# Generated by Django 5.2.3 on 2025-07-02 05:06

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_todoitem_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={},
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, help_text='Dirección del cliente.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, help_text='Correo electrónico del cliente.', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización del cliente.'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del cliente.'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre_empresa',
            field=models.CharField(help_text='Nombre de la empresa o cliente.', max_length=255),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, help_text='Número de teléfono del cliente.', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título o nombre de la cotización/oportunidad.', max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación de la cotización.')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización de la cotización.')),
                ('notas', models.TextField(blank=True, help_text='Notas generales para la cotización.', null=True)),
                ('comentarios', models.TextField(blank=True, help_text='Comentarios internos sobre la cotización.', null=True)),
                ('probabilidad_cierre', models.IntegerField(choices=[(0, '0% - Perdida'), (10, '10% - Muy Baja'), (25, '25% - Baja'), (50, '50% - Media'), (75, '75% - Alta'), (90, '90% - Muy Alta'), (100, '100% - Cerrada')], default=10, help_text='Probabilidad de cierre de la oportunidad')),
                ('mes_cierre', models.CharField(blank=True, choices=[('01', 'Enero'), ('02', 'Febrero'), ('03', 'Marzo'), ('04', 'Abril'), ('05', 'Mayo'), ('06', 'Junio'), ('07', 'Julio'), ('08', 'Agosto'), ('09', 'Septiembre'), ('10', 'Octubre'), ('11', 'Noviembre'), ('12', 'Diciembre')], help_text='Mes de cierre esperado para esta oportunidad', max_length=2, null=True)),
                ('area', models.CharField(blank=True, choices=[('VENTAS', 'Ventas'), ('MARKETING', 'Marketing'), ('SOPORTE', 'Soporte'), ('FINANZAS', 'Finanzas'), ('OTRO', 'Otro')], help_text='Área relacionada con la oportunidad', max_length=50, null=True)),
                ('producto', models.CharField(blank=True, choices=[('SOFTWARE', 'Software'), ('HARDWARE', 'Hardware'), ('SERVICIOS', 'Servicios'), ('CONSULTORIA', 'Consultoría'), ('LICENCIAS', 'Licencias'), ('MANTENIMIENTO', 'Mantenimiento'), ('OTRO', 'Otro')], help_text='Tipo de producto/servicio principal de la cotización', max_length=50, null=True)),
                ('monto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto total de la oportunidad (puede ser calculado o manual)', max_digits=10)),
                ('tipo_iva', models.CharField(choices=[('16', '16%'), ('8', '8%'), ('0', '0% (Exento)')], default='16', help_text='Tipo de IVA a aplicar (16% o 8%).', max_length=5)),
                ('moneda', models.CharField(choices=[('MXN', 'Pesos Mexicanos (MXN)'), ('USD', 'Dólares Americanos (USD)')], default='MXN', help_text='Moneda de la cotización.', max_length=3)),
                ('cliente', models.ForeignKey(help_text='Cliente al que pertenece esta cotización.', on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='app.cliente')),
                ('creado_por', models.ForeignKey(blank=True, help_text='Usuario que creó la cotización.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
            },
        ),
        migrations.CreateModel(
            name='ItemCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(help_text='Nombre del producto o servicio.', max_length=255)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del producto o servicio.', null=True)),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio unitario del producto.', max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Descuento aplicado al producto (en porcentaje, ej. 10.00 para 10%).', max_digits=5)),
                ('cantidad', models.PositiveIntegerField(default=1, help_text='Cantidad de este producto.')),
                ('cotizacion', models.ForeignKey(help_text='Cotización a la que pertenece este ítem.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.cotizacion')),
            ],
            options={
                'verbose_name': 'Ítem de Cotización',
                'verbose_name_plural': 'Ítems de Cotización',
            },
        ),
        migrations.DeleteModel(
            name='TodoItem',
        ),
    ]
