# Generated by Django 5.2.3 on 2025-07-03 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_itemcotizacion_cotizacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nombre_empresa'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='todoitem',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Oportunidad de Venta', 'verbose_name_plural': 'Oportunidades de Venta'},
        ),
        migrations.AlterField(
            model_name='cliente',
            name='asignado_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='contacto_principal',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Contacto Principal'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre_empresa',
            field=models.CharField(max_length=200, unique=True, verbose_name='Nombre de la Empresa'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='area',
            field=models.CharField(choices=[('IT', 'IT'), ('Finanzas', 'Finanzas'), ('Recursos Humanos', 'Recursos Humanos'), ('Marketing', 'Marketing'), ('Ventas', 'Ventas'), ('Operaciones', 'Operaciones'), ('Legal', 'Legal'), ('Administración', 'Administración'), ('Producción', 'Producción'), ('Logística', 'Logística'), ('Investigación y Desarrollo', 'Investigación y Desarrollo'), ('Servicio al Cliente', 'Servicio al Cliente'), ('Compras', 'Compras'), ('Calidad', 'Calidad'), ('Ingeniería', 'Ingeniería'), ('Consultoría', 'Consultoría'), ('Educación', 'Educación'), ('Salud', 'Salud'), ('Gobierno', 'Gobierno'), ('Telecomunicaciones', 'Telecomunicaciones'), ('Automotriz', 'Automotriz'), ('Energía', 'Energía'), ('Construcción', 'Construcción'), ('Retail', 'Retail'), ('Turismo', 'Turismo'), ('Medios', 'Medios'), ('Banca', 'Banca'), ('Seguros', 'Seguros'), ('Manufactura', 'Manufactura'), ('Farmacéutica', 'Farmacéutica'), ('Alimentos y Bebidas', 'Alimentos y Bebidas'), ('Bienes Raíces', 'Bienes Raíces'), ('Transporte', 'Transporte'), ('Agricultura', 'Agricultura'), ('Minería', 'Minería'), ('Entretenimiento', 'Entretenimiento'), ('Moda', 'Moda'), ('Deportes', 'Deportes'), ('Arte y Cultura', 'Arte y Cultura'), ('ONG', 'ONG (Organización No Gubernamental)'), ('Otro', 'Otro')], max_length=50, verbose_name='Área'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oportunidades', to='app.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='comentarios',
            field=models.TextField(blank=True, null=True, verbose_name='Comentarios'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='contacto',
            field=models.CharField(default=1, max_length=100, verbose_name='Contacto del Cliente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='mes_cierre',
            field=models.CharField(choices=[('01', 'Enero'), ('02', 'Febrero'), ('03', 'Marzo'), ('04', 'Abril'), ('05', 'Mayo'), ('06', 'Junio'), ('07', 'Julio'), ('08', 'Agosto'), ('09', 'Septiembre'), ('10', 'Octubre'), ('11', 'Noviembre'), ('12', 'Diciembre')], max_length=2, verbose_name='Mes de Cierre Esperado'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto de la Oportunidad'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='oportunidad',
            field=models.CharField(max_length=200, verbose_name='Oportunidad de Venta'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='probabilidad_cierre',
            field=models.IntegerField(verbose_name='Probabilidad de Cierre (%)'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='producto',
            field=models.CharField(choices=[('Software CRM', 'Software CRM'), ('Servicios de Consultoría', 'Servicios de Consultoría'), ('Hardware de Red', 'Hardware de Red'), ('Soluciones Cloud', 'Soluciones Cloud'), ('Desarrollo Web', 'Desarrollo Web'), ('Mantenimiento de Sistemas', 'Mantenimiento de Sistemas'), ('Seguridad Informática', 'Seguridad Informática'), ('Análisis de Datos', 'Análisis de Datos'), ('Licencias de Software', 'Licencias de Software'), ('Soporte Técnico', 'Soporte Técnico'), ('Integración de Sistemas', 'Integración de Sistemas'), ('Capacitación TI', 'Capacitación TI'), ('Hosting y Dominios', 'Hosting y Dominios'), ('Marketing Digital', 'Marketing Digital'), ('Desarrollo de Apps Móviles', 'Desarrollo de Apps Móviles'), ('E-commerce Solutions', 'E-commerce Solutions'), ('ERP Implementation', 'ERP Implementation'), ('Business Intelligence', 'Business Intelligence'), ('Cloud Migration', 'Cloud Migration'), ('IT Staffing', 'IT Staffing'), ('Cybersecurity Audit', 'Cybersecurity Audit'), ('Data Warehousing', 'Data Warehousing'), ('Network Infrastructure', 'Network Infrastructure'), ('Managed IT Services', 'Managed IT Services'), ('IT Consulting', 'IT Consulting'), ('Software Development', 'Software Development'), ('Web Design', 'Web Design'), ('Database Management', 'Database Management'), ('Virtualization Solutions', 'Virtualization Solutions'), ('IT Project Management', 'IT Project Management'), ('Digital Transformation', 'Digital Transformation'), ('AI/ML Solutions', 'AI/ML Solutions'), ('IoT Solutions', 'IoT Solutions'), ('Blockchain Development', 'Blockchain Development'), ('Robotic Process Automation', 'Robotic Process Automation'), ('Big Data Solutions', 'Big Data Solutions'), ('DevOps Consulting', 'DevOps Consulting'), ('UI/UX Design', 'UI/UX Design'), ('API Development', 'API Development'), ('System Integration', 'System Integration'), ('IT Training', 'IT Training'), ('Cloud Security', 'Cloud Security'), ('Data Recovery', 'Data Recovery'), ('Backup Solutions', 'Backup Solutions'), ('IT Audit', 'IT Audit'), ('IT Governance', 'IT Governance'), ('IT Strategy', 'IT Strategy'), ('Digital Marketing', 'Digital Marketing'), ('Content Creation', 'Content Creation'), ('SEO Services', 'SEO Services'), ('Social Media Management', 'Social Media Management'), ('Email Marketing', 'Email Marketing'), ('PPC Advertising', 'PPC Advertising'), ('Branding', 'Branding'), ('Public Relations', 'Public Relations'), ('Market Research', 'Market Research'), ('Sales Training', 'Sales Training'), ('Customer Service Training', 'Customer Service Training'), ('Financial Consulting', 'Financial Consulting'), ('Accounting Services', 'Accounting Services'), ('Tax Consulting', 'Tax Consulting'), ('Legal Consulting', 'Legal Consulting'), ('HR Consulting', 'HR Consulting'), ('Recruitment Services', 'Recruitment Services'), ('Supply Chain Management', 'Supply Chain Management'), ('Logistics Consulting', 'Logistics Consulting'), ('Operations Consulting', 'Operations Consulting'), ('Project Management', 'Project Management'), ('Quality Management', 'Quality Management'), ('Engineering Services', 'Engineering Services'), ('Manufacturing Consulting', 'Manufacturing Consulting'), ('Research & Development', 'Research & Development'), ('Environmental Consulting', 'Environmental Consulting'), ('Energy Consulting', 'Energía'), ('Construction Management', 'Construction Management'), ('Real Estate Consulting', 'Real Estate Consulting'), ('Healthcare Consulting', 'Healthcare Consulting'), ('Education Consulting', 'Education Consulting'), ('Government Consulting', 'Government Consulting'), ('Telecommunications Consulting', 'Telecomunicaciones'), ('Automotive Consulting', 'Automotriz'), ('Retail Consulting', 'Retail Consulting'), ('Tourism Consulting', 'Turismo'), ('Media Consulting', 'Medios'), ('Banking Consulting', 'Banca'), ('Insurance Consulting', 'Seguros'), ('Pharmaceutical Consulting', 'Farmacéutica'), ('Food & Beverage Consulting', 'Alimentos y Bebidas'), ('Agriculture Consulting', 'Agricultura'), ('Mining Consulting', 'Minería'), ('Entertainment Consulting', 'Entretenimiento'), ('Fashion Consulting', 'Moda'), ('Sports Consulting', 'Deportes'), ('Art & Culture Consulting', 'Arte y Cultura'), ('Non-Profit Consulting', 'ONG (Organización No Gubernamental)'), ('Otro', 'Otro')], max_length=100, verbose_name='Producto / Servicio'),
        ),
    ]
