# Generated by Django 5.2.3 on 2025-07-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_cliente_options_alter_todoitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='area',
            field=models.CharField(choices=[('SISTEMAS', 'Sistemas'), ('Recursos Humanos', 'Recursos Humanos'), ('Compras', 'Compras'), ('Seguridad', 'Seguridad'), ('Mantenimiento', 'Mantenimiento'), ('Almacén', 'Almacén')], max_length=50, verbose_name='Área'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='producto',
            field=models.CharField(choices=[('ZEBRA', 'ZEBRA'), ('AXIS', 'AXIS'), ('AVIGILION', 'AVIGILION'), ('CISCO', 'CISCO'), ('GENETEC', 'GENETEC'), ('SOFTWARE', 'SOFTWARE'), ('SERVICIOS', 'SERVICIOS'), ('PÓLIZA', 'PÓLIZA'), ('RUNRATE', 'RUNRATE')], max_length=100, verbose_name='Producto / Servicio'),
        ),
    ]
