# Generated by Django 5.2.3 on 2025-07-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_cotizacion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción General de la Cotización'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='nombre_cotizacion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre para el PDF de la Cotización'),
        ),
    ]
