# Generated by Django 5.2.3 on 2025-07-06 22:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_cotizacion_descripcion_cotizacion_nombre_cotizacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='iva_amount',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='nombre_cotizacion',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='total',
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='institucion',
            field=models.CharField(choices=[('BAJANET', 'BAJANET'), ('IAMET', 'IAMET')], default='BAJANET', max_length=10, verbose_name='Institución'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='iva_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.1600'), max_digits=5, verbose_name='Tasa de IVA'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='moneda',
            field=models.CharField(choices=[('MXN', 'Pesos (MXN)'), ('USD', 'Dólares (USD)')], default='USD', max_length=5, verbose_name='Moneda'),
        ),
    ]
