# Generated by Django 5.2.3 on 2025-07-06 22:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_cotizacion_iva_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='institucion',
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='iva_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Monto de IVA'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='nombre_cotizacion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre para el PDF de la Cotización'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Subtotal'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='iva_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.16'), max_digits=5, verbose_name='Tasa de IVA'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='moneda',
            field=models.CharField(default='USD', max_length=5, verbose_name='Moneda'),
        ),
    ]
