# Generated by Django 5.2.3 on 2025-07-06 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_cotizacion_institucion_cotizacion_iva_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='tipo_cotizacion',
            field=models.CharField(choices=[('Bajanet', 'Bajanet'), ('Iamet', 'Iamet')], default='Bajanet', max_length=10, verbose_name='Tipo de Cotización'),
        ),
    ]
